version: "3"

services:
  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  front-nextjs:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.front
    command: npm start
    expose:
      - 3000
