version: '3'

services:
  api-server:
    extends:
      file: docker-compose.base.yml
      service: mydomain-base
    command: node ./api-server/main.js
    expose:
      - 8888
    depends_on:
      - postgresql
      - redis
    networks:
      - mydomain_net

  parsing-batch:
    extends:
      file: docker-compose.base.yml
      service: mydomain-base
    command: node ./parsing-batch/main.js
    expose:
      - 8889
    depends_on:
      - postgresql
      - redis
    networks:
      - mydomain_net

  postgresql:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DB: mydomain
    expose:
      - 5432
    volumes:
      - mydomain_postgres_data:/var/lib/postgresql/data
    networks:
      - mydomain_net

  redis:
    image: redis:7.0.12
    restart: always
    expose:
      - 6379
    networks:
      - mydomain_net

volumes:
  mono-node-modules: null
  mydomain_postgres_data:

networks:
  mydomain_net:
    driver: bridge
